const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const base=process.env.DEMO_UI_URL;
if (!base || !process.env.DEMO_UI_PASSWORD) throw new Error('Run through scripts/test_recruitment_ui.py');
const output=path.resolve(__dirname,'../test-results'); fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined,args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--no-zygote'],headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);
 await page.getByRole('button',{name:'Start a demo application'}).waitFor();
 await page.waitForFunction(()=>!document.querySelector('.recruit-primary').disabled);
 await page.screenshot({path:path.join(output,'home-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Start a demo application'}).click();
 await page.getByRole('button',{name:'Fill fictional example'}).click();
 const email=await page.locator('[name=contact_email]').inputValue();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.getByRole('button',{name:'Back',exact:true}).click();
 assert(await page.locator('[name=demo_online_access][value=true]').isChecked());
 await page.getByRole('button',{name:'Continue',exact:true}).click();
 await page.locator('[name=consent_to_screen]').check();
 await page.locator('[name=privacy_acknowledged]').check();
 await page.getByRole('button',{name:'Submit demo application'}).click();
 await page.getByText('Submitted successfully').waitFor();
 const ref=await page.locator('.recruit-receipt h2').textContent();
 const token=await page.getByLabel('Private access key').inputValue();
 const download=page.waitForEvent('download'); await page.getByRole('button',{name:'Download receipt'}).click();
 assert.equal((await download).suggestedFilename(),`${ref}-receipt.txt`);
 await page.getByRole('button',{name:'Check application status'}).click();
 await page.getByRole('heading',{name:'Application received',exact:true}).waitFor();
 await page.reload();
 assert.equal(await page.locator('[name=access_token]').inputValue(),'');
 await page.locator('[name=reference_code]').fill(ref);
 await page.locator('[name=access_token]').fill('x'.repeat(43));
 await page.getByRole('button',{name:'Check status',exact:true}).click();
 await page.getByRole('alert').filter({hasText:'not recognised'}).waitFor();
 await page.locator('[name=access_token]').fill(token);
 await page.getByRole('button',{name:'Check status',exact:true}).click();
 await page.getByRole('heading',{name:'Application received',exact:true}).waitFor();
 await page.screenshot({path:path.join(output,'status-desktop.png'),fullPage:true});
 // The main lifecycle uses the real backend and a disposable database.
 const staff=await browser.newPage({viewport:{width:1440,height:1000}});
 staff.on('pageerror',e=>errors.push(e.message));
 await staff.goto(base+'/#signin');
 await staff.getByLabel('Email',{exact:true}).fill('admin@example.com');
 await staff.getByLabel('Password',{exact:true}).fill(process.env.DEMO_UI_PASSWORD);
 await staff.getByRole('button',{name:'Sign in',exact:true}).click();
 await staff.getByRole('button',{name:'Recruitment',exact:true}).click();
 await staff.getByLabel('Search applicants').fill(ref);
 await staff.getByRole('button').filter({hasText:ref}).click();
 await staff.locator('select[name=status]').selectOption('eligible');
 await staff.getByRole('button',{name:'Save eligibility review'}).click();
 await staff.getByText(`Review saved for ${ref}.`).waitFor();
 await staff.getByRole('button',{name:'Save selection'}).click();
 await staff.getByText(`Selection saved for ${ref}.`).waitFor();
 await staff.getByRole('button',{name:'Enroll participant',exact:true}).click();
 await staff.getByText('Participant enrolled',{exact:true}).waitFor();
 await staff.screenshot({path:path.join(output,'staff-review.png'),fullPage:true});
 const participantCode=await staff.locator('.enrollment-success>span').textContent();
 await staff.getByRole('button',{name:'Participants',exact:true}).click();
 await staff.getByLabel('Search participant code or ID').fill(participantCode);
 await staff.getByRole('button',{name:'View details',exact:true}).click();
 await staff.getByRole('button',{name:'Run server-side allocation',exact:true}).click();
 await staff.locator('.participant-row .tag').filter({hasText:/^(HumorBot|STARCASM|Control)$/}).waitFor();
 await staff.locator('[name=email]').fill(email);
 await staff.locator('[name=full_name]').fill('Fictional Browser Participant');
 await staff.locator('[name=initial_password]').fill(process.env.DEMO_UI_PASSWORD);
 await staff.getByRole('button',{name:'Create or link account',exact:true}).click();
 await staff.getByText('Linked to participant-only login',{exact:true}).waitFor();
 await staff.reload();
 await staff.getByRole('button',{name:'Participants',exact:true}).click();
 await staff.getByLabel('Search participant code or ID').fill(participantCode);
 await staff.getByRole('button',{name:'View details',exact:true}).click();
 await staff.getByText('Linked to participant-only login',{exact:true}).waitFor();
 const portal=await browser.newPage();
 portal.on('pageerror',e=>errors.push(e.message));
 await portal.goto(base+'/#signin');
 await portal.getByLabel('Email',{exact:true}).fill(email);
 await portal.getByLabel('Password',{exact:true}).fill(process.env.DEMO_UI_PASSWORD);
 await portal.getByRole('button',{name:'Sign in',exact:true}).click();
 await portal.getByRole('heading',{name:'My study',exact:true}).waitFor();
 await portal.getByText(participantCode,{exact:true}).waitFor();
 assert.equal(await portal.getByRole('button',{name:'Recruitment',exact:true}).count(),0);
 assert.equal(await portal.getByRole('button',{name:'Admin',exact:true}).count(),0);
 await portal.reload();
 await portal.getByText(participantCode,{exact:true}).waitFor();

 // Complete the new synthetic study flow and verify persistence and staff results.
 await portal.getByRole('heading',{name:'Pre-test',exact:true}).waitFor();
 await portal.screenshot({path:path.join(output,'study-pre-test.png'),fullPage:true});
 for(let i=0;i<4;i++) await portal.locator(`input[name="q-${i}"]`).first().check();
 await portal.locator('input[type=checkbox]').check();
 await portal.getByRole('button',{name:'Submit pre-test',exact:true}).click();
 for(let n=1;n<=3;n++) {
   await portal.getByRole('heading',{name:`Session ${n}`,exact:true}).waitFor();
   await portal.getByLabel('Time spent (minutes)').fill('5');
   await portal.getByLabel('Help received').selectOption('none');
   await portal.getByLabel('How did the session feel?').selectOption(n===2?'tiring':'comfortable');
   await portal.locator('input[type=checkbox]').check();
   await portal.getByRole('button',{name:`Submit session ${n}`,exact:true}).click();
 }
 await portal.getByRole('heading',{name:'Post-test',exact:true}).waitFor();
 for(let i=0;i<4;i++) await portal.locator(`input[name="q-${i}"]`).first().check();
 await portal.locator('input[type=checkbox]').check();
 await portal.getByRole('button',{name:'Submit post-test',exact:true}).click();
 await portal.getByRole('heading',{name:'All demo steps are complete',exact:true}).waitFor();
 await portal.reload();
 await portal.getByRole('heading',{name:'All demo steps are complete',exact:true}).waitFor();
 await staff.getByRole('button',{name:'Results',exact:true}).click();
 await staff.getByRole('heading',{name:'Study results',exact:true}).waitFor();
 await staff.getByPlaceholder('Participant code',{exact:true}).fill(participantCode);
 await staff.getByText('Comfort review needed',{exact:true}).waitFor();
 const studyRow=staff.locator('.wf-table tbody tr');
 assert.equal(await studyRow.count(),1);
 assert((await studyRow.textContent()).includes('3 / 3'));
 await staff.screenshot({path:path.join(output,'study-results.png'),fullPage:true});
 const csv=staff.waitForEvent('download');
 await staff.getByRole('button',{name:'Export shown rows (CSV)',exact:true}).click();
 assert.equal((await csv).suggestedFilename(),'synthetic-study-progress.csv');

 await page.getByRole('button',{name:'Check status',exact:true}).click();
 await page.getByRole('heading',{name:'Login access ready',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Withdraw this application'}).count(),0);
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 mobile.on('pageerror',e=>errors.push(e.message));
 await mobile.goto(base);
 await mobile.waitForFunction(()=>!document.querySelector('.recruit-primary').disabled);
 assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await mobile.screenshot({path:path.join(output,'home-mobile.png'),fullPage:true});
 await mobile.getByRole('button',{name:'Start a demo application'}).click();
 await mobile.getByRole('button',{name:'Fill fictional example'}).click();
 await mobile.screenshot({path:path.join(output,'application-mobile.png'),fullPage:true});
 await mobile.getByRole('button',{name:'Continue',exact:true}).click();
 await mobile.getByRole('button',{name:'Continue',exact:true}).click();
 await mobile.locator('[name=consent_to_screen]').check();
 await mobile.locator('[name=privacy_acknowledged]').check();
 await mobile.getByRole('button',{name:'Submit demo application'}).click();
 await mobile.getByText('Submitted successfully').waitFor();
 await mobile.getByRole('button',{name:'Check application status'}).click();
 await mobile.getByRole('button',{name:'Withdraw this application'}).click();
 await mobile.getByRole('button',{name:'Keep application'}).click();
 await mobile.getByRole('button',{name:'Withdraw this application'}).click();
 await mobile.getByRole('button',{name:'Confirm withdrawal'}).click();
 await mobile.getByRole('heading',{name:'Withdrawn',exact:true}).waitFor();
 assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 // Deliberately interrupt public info to verify a recoverable network error.
 const outage=await browser.newPage();
 await outage.route('**/api/public/recruitment/info',route=>route.abort());
 await outage.goto(base);
 await outage.getByRole('alert').filter({hasText:'Recruitment service unavailable'}).waitFor();
 await outage.unroute('**/api/public/recruitment/info');
 await outage.getByRole('button',{name:'Retry connection'}).click();
 await outage.waitForFunction(()=>!document.querySelector('.recruit-primary').disabled);
 assert.deepEqual(errors,[]);
 console.log('PASS desktop application, receipt, fresh-page status, invalid key, staff review/selection/enrollment/allocation/account link, participant login and refresh, applicant status transition, mobile application/withdrawal, no horizontal overflow, no JS errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
