import { useState } from 'react';
import rawSource from './screening-draft.json';
import feedbackSource from './participant-feedback.json';
import './assessment-draft.css';

type Answers = Record<string, string | string[]>;
type Part = {kind:string; label:string; options?:string[]; when_yes?:boolean; other_for?:number};
const source: {version:string; source:string; source_sha256:string; items:{number:number; section:string; prompt:string; parts:Part[]}[]; staff_groups:Part[]} = rawSource;
type Result = {id:string; participant:string; visit:string; instrument:string; form:string; language:string; date:string; assessor:string; status:string; total:string; maximum:string; adjustment:string; guide:string; secondsA:string; secondsB:string; statusA:string; statusB:string; errorsA:string; errorsB:string; notes:string};
const emptyResult = (participant:string):Result => ({id:'',participant,visit:'Baseline',instrument:'MoCA',form:'MoCA 8.3 English (2018)',language:'English',date:'',assessor:'',status:'',total:'',maximum:'',adjustment:'',guide:'',secondsA:'',secondsB:'',statusA:'',statusB:'',errorsA:'',errorsB:'',notes:''});
const isPresent = (v:unknown) => Array.isArray(v) ? v.length > 0 : typeof v === 'string' && v.trim() !== '';
function download(value:unknown) {
  const a=document.createElement('a'), url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));
  a.href=url; a.download='assessment-review-draft.json'; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function AssessmentDraft() {
 const [tab,setTab]=useState('overview'),[answers,setAnswers]=useState<Answers>({}),[participant,setParticipant]=useState('');
 const [completedBy,setCompletedBy]=useState(''),[site,setSite]=useState(''),[screenDate,setScreenDate]=useState('');
 const [staff,setStaff]=useState<Answers>({}),[result,setResult]=useState<Result>(emptyResult('')),[results,setResults]=useState<Result[]>([]);
 const [notice,setNotice]=useState('');
 const [feedback,setFeedback]=useState<Record<string,string>>({}),[feedbackNotes,setFeedbackNotes]=useState('');
 const [ack,setAck]=useState(false),[group,setGroup]=useState('STARCASM'),[reply,setReply]=useState(''),[sessions,setSessions]=useState<{id:string;participant:string;group:string;prompt:string;reply:string;response:string;at:string;simulated:boolean}[]>([]);
 const [startDate,setStartDate]=useState('2026-10-08');
 const prompt = group==='STARCASM'?'A person says “Wonderful weather!” while standing in heavy rain. What might they mean?':group==='HumorBot'?'Why might “I used to be a baker, but I could not make enough dough” be amusing?':'Describe one everyday activity you enjoy.';
 const scriptedResponse=group==='STARCASM'?'This example may be sarcastic because the positive words contrast with the rainy situation.':group==='HumorBot'?'This example plays on two meanings of dough: bread mixture and money.':'Thank you. This neutral activity illustrates the control workflow.';
 const followUp=(()=>{if(!startDate)return '';const [y,m,d]=startDate.split('-').map(Number);const target=new Date(Date.UTC(y,m-1+3,1));target.setUTCDate(Math.min(d,new Date(Date.UTC(target.getUTCFullYear(),target.getUTCMonth()+1,0)).getUTCDate()));return target.toISOString().slice(0,10);})();
 const plan={version:'committee-demo-v2',status:'provisional_committee_irb_review',baseline:['MoCA 8.3 English (2018)','Trail Making A/B - IowaTrailMaking.pdf'],follow_up:['SAGE Form 1 - US 2021'],follow_up_replaces_baseline_tests:true,feedback_respondent:'participant',duration:'three calendar months',start_date:startDate,illustrative_follow_up_date:followUp,session_frequency:'not finalized',scoring:'manual fictional result entry; no automated clinical scoring',digit_span:'separate demonstration game; excluded from cognitive change calculations'};
 function saveSession(){if(!participant.trim()||!ack||!reply.trim()){setNotice('Enter a fictional code, acknowledge the demonstration, and type a sample reply.');return;}setSessions(v=>[...v,{id:crypto.randomUUID(),participant:participant.trim(),group,prompt,reply:reply.trim(),response:scriptedResponse,at:new Date().toISOString(),simulated:true}]);setReply('');setNotice('Scripted demonstration session recorded in this page. It is included in the JSON export.');}

 const put=(key:string,value:string|string[])=>setAnswers(a=>({...a,[key]:value}));
 const key=(n:number,i:number)=>`q${n}_${i}`;
 const q5=answers.q5_0;
 const shown=(n:number)=>n<6||n>17||q5==='Yes';
 function partShown(n:number,p:Part) {
  if(p.when_yes && answers[key(n,0)]!=='Yes') return false;
  if(p.other_for!==undefined) {const v=answers[key(n,p.other_for)]; return Array.isArray(v)?v.some(x=>x.startsWith('Other')):typeof v==='string'&&v.startsWith('Other');}
  return true;
 }
 function field(p:Part,id:string,value:string|string[]|undefined,change:(v:string|string[])=>void) {
  if(p.kind==='note')return <p key={id} className="draft-help">{p.label}</p>;
  if(p.kind==='multi')return <fieldset key={id}><legend>{p.label}</legend>{p.options!.map(o=><label className="draft-option" key={o}><input type="checkbox" checked={Array.isArray(value)&&value.includes(o)} onChange={e=>change(e.target.checked?[...(Array.isArray(value)?value:[]),o]:(Array.isArray(value)?value:[]).filter(x=>x!==o))}/>{o}</label>)}</fieldset>;
  return <label className="draft-field" key={id}>{p.label}{p.kind==='choice'?<select aria-label={id} value={typeof value==='string'?value:''} onChange={e=>change(e.target.value)}><option value="">Unanswered</option>{p.options!.map(o=><option key={o}>{o}</option>)}</select>:p.kind==='number'?<input aria-label={id} type="number" min="0" step="1" value={typeof value==='string'?value:''} onChange={e=>change(e.target.value)}/>:<textarea aria-label={id} rows={2} value={typeof value==='string'?value:''} onChange={e=>change(e.target.value)}/>}</label>;
 }
 function exportDraft(){
  if(!participant.trim()){setNotice('Enter a fictional participant code before export.');return;}
  for (const q of source.items) { if (!shown(q.number)) continue; for (const [i,p] of q.parts.entries()) { const v=answers[key(q.number,i)]; if(p.kind==='number' && isPresent(v) && (!Number.isInteger(Number(v)) || Number(v)<0)) {setNotice('Age fields must be nonnegative whole years or left unanswered.');return;} } }
  const responses=source.items.map(q=>({question:q.number,prompt:q.prompt,status:shown(q.number)?'recorded_or_unanswered':isPresent(q5)?'not_applicable':'routing_unanswered',fields:shown(q.number)?q.parts.filter(p=>p.kind!=='note').map(p=>{const i=q.parts.indexOf(p);return {id:key(q.number,i),label:p.label,status:partShown(q.number,p)?isPresent(answers[key(q.number,i)])?'answered':'unanswered':'not_applicable',value:partShown(q.number,p)?answers[key(q.number,i)]??null:null};}):[]}));
  download({schema_version:'assessment-review-v2',synthetic_only:true,protocol_status:'provisional_committee_irb_review',plan,demo_acknowledgement:ack,bot_sessions:sessions,participant_feedback:{participant_code:participant.trim(),respondent:'participant',source:feedbackSource.source,source_sha256:feedbackSource.source_sha256,version:feedbackSource.version,adaptation_status:feedbackSource.adaptation_status,responses:feedbackSource.items.map(q=>({...q,value:feedback[q.id]||null})),comments:feedbackNotes||null},exported_at:new Date().toISOString(),screening:{participant_code:participant.trim(),source_version:source.version,source_sha256:source.source_sha256,date:screenDate||null,completed_by:completedBy||null,site:site||null,responses,staff_review:staff},assessment_results:results,comparison:null});
  setNotice('Draft exported. Unanswered fields remain missing; no eligibility or cognitive change score is calculated.');
 }
 const edit=(name:keyof Result,value:string)=>setResult(r=>name==='instrument'?{...emptyResult(participant),instrument:value,visit:value==='SAGE'?'Three-month follow-up':'Baseline',form:value==='SAGE'?'SAGE Form 1 - US 2021':value==='Trail Making'?'Trail Making A/B - Iowa':'MoCA 8.3 English (2018)',guide:value==='Trail Making'?'IowaTrailMaking.pdf - provisional demo':value==='SAGE'?'Manual demo entry; scoring guide pending':''}:{...r,[name]:value});
 function resultField(label:string,name:keyof Result,options?:string[],type='text',required=false){return <label className="draft-field">{label}{options?<select aria-label={label} required={required} value={result[name]} onChange={e=>edit(name,e.target.value)}><option value="">Select…</option>{options.map(x=><option key={x}>{x}</option>)}</select>:<input aria-label={label} required={required} type={type} min={type==='number'?'0':undefined} step={type==='number'?(name==='errorsA'||name==='errorsB'?'1':'any'):undefined} value={result[name]} onChange={e=>edit(name,e.target.value)}/>}</label>;}
 return <section className="assessment-draft">
 <header><span className="draft-badge">Committee / IRB demonstration • Fictional data only</span><h2>Cognitive bot study walkthrough</h2><p>Explore the proposed three-month study using provisional forms and fictional records. Entries stay in memory until exported and disappear when this page reloads. This draft does not submit data to the study database.</p></header>
 <label className="draft-field">Fictional participant code<input value={participant} onChange={e=>setParticipant(e.target.value)} placeholder="DEMO-001"/></label>
 <nav aria-label="Draft forms">{[['overview','Study walkthrough'],['screening','Screening questionnaire'],['staff','Staff eligibility review'],['results','Test result entry'],['interaction','Bot interaction'],['feedback','Participant feedback'],['decisions','Provisional choices']].map(([id,label])=><button type="button" aria-pressed={tab===id} key={id} onClick={()=>{setTab(id);setNotice('');}}>{label}</button>)}</nav>
 {notice&&<p role="status">{notice}</p>}
 {tab==='overview'&&<div>
 <h3>Proposed participant journey</h3><ol className="demo-journey"><li><strong>Screening and consent</strong><p>Participant screening, staff eligibility review, and an approved consent process before enrollment. This page does not obtain research consent.</p></li><li><strong>Baseline assessment</strong><p>MoCA 8.3 and Trail Making A/B (Iowa instructions). Staff enter results from separately administered tests.</p></li><li><strong>Assigned study activities</strong><p>Illustrative STARCASM, HumorBot or control sessions over three months. Frequency and duration remain provisional.</p></li><li><strong>Follow-up assessment</strong><p>SAGE Form 1 replaces MoCA and Trail Making at follow-up. Scores stay separate by instrument.</p></li><li><strong>Participant feedback and export</strong><p>Participants rate their experience. Export screening, results, scripted session records and feedback together.</p></li></ol>
 <div className="draft-grid"><label className="draft-field">Illustrative baseline date<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><p>Illustrative three-month follow-up: <strong>{followUp||'Choose a date'}</strong>. Dates are for demonstration only.</p></div>
 <label className="draft-option"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I understand this is a fictional demonstration, not study enrollment or consent.</label>
 <p><a href="/digit-span.html" target="_blank" rel="noreferrer">Open the existing Digit Span game</a> in a separate tab. Its game results are not part of this assessment export.</p>
 <button onClick={()=>setTab('screening')}>Begin screening walkthrough</button>
 </div>}
 {tab==='interaction'&&<div><h3>Illustrative bot interaction</h3><p>This scripted example demonstrates the interaction screen and logging. It does not call a trained bot, assess your reply, or represent a completed three-month intervention.</p><label className="draft-field">Demonstration group<select value={group} onChange={e=>{setGroup(e.target.value);setReply('');}}>{['STARCASM','HumorBot','Control'].map(x=><option key={x}>{x}</option>)}</select></label><p>Group selection is for demonstration only; real allocation is performed separately.</p><blockquote>{prompt}</blockquote><label className="draft-field">Fictional participant reply<textarea rows={3} value={reply} onChange={e=>setReply(e.target.value)}/></label><button onClick={saveSession}>Record scripted session</button><h3>Recorded demonstration sessions ({sessions.length})</h3>{sessions.map(s=><article className="draft-question" key={s.id}><strong>{s.participant} · {s.group}</strong><p>Participant: {s.reply}</p><p>Scripted response: {s.response}</p></article>)}</div>}
 {tab==='feedback'&&<div><h3>Participant feedback questionnaire</h3><p>Complete from the participant perspective. Technology and chatbot items use 1 (disagree) to 5 (agree); usability items use 1 (strongly disagree) to 7 (strongly agree), preserving the supplied direction. Leave unanswered or select Not applicable when the experience does not apply.</p><p className="draft-help">Provisional adaptation of Research Tool 1.pdf: DigiMoCA references and administrator wording are adapted to this study platform; staff demographics are omitted. No validated or composite score is claimed.</p>{feedbackSource.items.map((q,i)=><div key={q.id}>{(i===0||feedbackSource.items[i-1].group!==q.group)&&<h3>{q.group}</h3>}<label className="draft-field">{q.number}. {q.prompt}<select aria-label={q.id} value={feedback[q.id]||''} onChange={e=>setFeedback(v=>({...v,[q.id]:e.target.value}))}><option value="">Unanswered</option>{Array.from({length:q.maximum},(_,n)=><option key={n+1} value={String(n+1)}>{n+1}{n===0?' — disagree':n+1===q.maximum?' — agree':''}</option>)}<option value="not_applicable">Not applicable</option></select></label></div>)}<label className="draft-field">Positive or negative aspects (optional)<textarea rows={3} value={feedbackNotes} onChange={e=>setFeedbackNotes(e.target.value)}/></label></div>}
 {tab==='screening'&&<div>
  <h3>Brain Injury and Cognitive Impairment Participant Screening Questionnaire</h3>
  <p>Purpose: Preliminary screening of potential participants with a history of brain injury, neurological injury, or cognitive impairment.</p>
  <div className="draft-grid"><label className="draft-field">Screening date<input type="date" value={screenDate} onChange={e=>setScreenDate(e.target.value)}/></label><label className="draft-field">Completed by<select value={completedBy} onChange={e=>setCompletedBy(e.target.value)}><option value="">Unanswered</option>{['Participant','Caregiver/Family Member','Research Staff'].map(x=><option key={x}>{x}</option>)}</select></label><label className="draft-field">Screening site<input value={site} onChange={e=>setSite(e.target.value)}/></label></div>
  {source.items.map((q,index)=><div key={q.number}>{(index===0||source.items[index-1].section!==q.section)&&<h3>{q.section}</h3>}{shown(q.number)?<section className="draft-question"><h4>{q.number}. {q.prompt}</h4>{q.number===5&&<p>Answer Questions 6–17 only if Yes.</p>}{q.parts.map((p,i)=>partShown(q.number,p)?field(p,key(q.number,i),answers[key(q.number,i)],v=>put(key(q.number,i),v)):null)}</section>:q.number===6?<p>Questions 6–17 are shown when Question 5 is Yes.</p>:null}</div>)}
 </div>}
 {tab==='staff'&&<div><h3>Section G — Preliminary Research Eligibility</h3><p>Research staff only — do not complete as participant self-diagnosis. No automatic eligibility rules have been applied.</p>{source.staff_groups.map((p,i)=>field(p,`staff_${i}`,staff[`staff_${i}`],v=>setStaff(s=>({...s,[`staff_${i}`]:v}))))}{['Reason/comments','Screened by','Date'].map(label=>field({kind:'text',label},label,staff[label],v=>setStaff(s=>({...s,[label]:v}))))}</div>}
 {tab==='results'&&<div><h3>Separate test result entry</h3><p>Enter results from an assessment administered outside this draft. The fields below are proposed record fields; they do not administer or score the tests. Choose the visit and exact form explicitly.</p>
 <form onSubmit={e=>{e.preventDefault();
  if(!participant.trim()){setNotice('Enter a fictional participant code first.');return;}
  if((result.instrument==='SAGE') !== (result.visit==='Three-month follow-up')){setNotice('This provisional plan uses MoCA and Trail Making at baseline, and SAGE only at follow-up.');return;}
  if(result.instrument==='Trail Making' && ((result.status==='Completed' && (result.statusA!=='Completed'||result.statusB!=='Completed')) || (result.status==='Not administered' && (result.statusA!=='Not administered'||result.statusB!=='Not administered')) || (result.status==='Incomplete' && result.statusA==='Completed' && result.statusB==='Completed'))) {setNotice('Overall administration status must agree with the Part A and Part B statuses.');return;}
  if(result.instrument!=='Trail Making'&&result.status==='Completed'&&result.total!==''&&result.maximum!==''&&Number(result.total)>Number(result.maximum)){setNotice('The entered total exceeds the entered maximum.');return;}
  if(results.some(r=>r.participant===participant.trim()&&r.visit===result.visit&&r.instrument===result.instrument)){setNotice('A draft result already exists for this participant, visit and instrument. Remove it before replacing it.');return;}
  const r={...result,id:crypto.randomUUID(),participant:participant.trim()};
  if(r.instrument==='Trail Making'){r.total='';r.maximum='';r.adjustment='';if(r.statusA!=='Completed')r.secondsA='';if(r.statusB!=='Completed')r.secondsB='';}
  else {r.secondsA='';r.secondsB='';r.errorsA='';r.errorsB='';r.statusA='';r.statusB='';if(r.status!=='Completed'){r.total='';r.maximum='';r.adjustment='';}}
  setResults(s=>[...s,r]);setResult(emptyResult(participant));setNotice('Draft result added. It has not been saved to the study database.');
 }}>
 <div className="draft-grid">
 {resultField('Instrument','instrument',['MoCA','Trail Making','SAGE'],'text',true)}{resultField('Visit','visit',result.instrument==='SAGE'?['Three-month follow-up']:['Baseline'],'text',true)}
 {resultField('Form / version','form',undefined,'text',true)}{resultField('Language','language',undefined,'text',true)}{resultField('Assessment date','date',undefined,'date',true)}{resultField('Assessor code','assessor',undefined,'text',true)}{resultField('Administration status','status',['Completed','Incomplete','Not administered'],'text',true)}{resultField('Administration / scoring guide reference','guide')}
 </div>
 {result.instrument==='Trail Making'?<div className="draft-grid">{(['A','B'] as const).map(p=><fieldset key={p}><legend>Trail Making Part {p}</legend>{resultField(`Part ${p} status`,`status${p}`,['Completed','Stopped','Not administered'],'text',true)}{result[`status${p}`]==='Completed'&&resultField(`Part ${p} completion time in seconds`,`seconds${p}`,undefined,'number',true)}{resultField(`Part ${p} error count`,`errors${p}`,undefined,'number')}</fieldset>)}</div>:result.status==='Completed'?<div className="draft-grid">{resultField('Recorded total','total',undefined,'number',true)}{resultField('Maximum entered by assessor','maximum',undefined,'number')}{resultField('Adjustments applied by assessor','adjustment')}</div>:<p>No completed score will be exported for this status.</p>}
 {resultField('Notes / missingness or stopping reason','notes')}
 <button type="submit">Add draft result</button>
 </form>
 <h3>Draft results ({results.length})</h3>{results.map(r=><div className="draft-record" key={r.id}><span>{r.participant} · {r.visit} · {r.instrument} · {r.form} · {r.status}</span><button type="button" onClick={()=>setResults(s=>s.filter(x=>x.id!==r.id))}>Remove {r.instrument} {r.visit}</button></div>)}
 </div>}
 {tab==='decisions'&&<div><h3>Provisional demonstration choices</h3><ul><li>Baseline: MoCA 8.3 English and Trail Making A/B using IowaTrailMaking.pdf.</li><li>Follow-up: SAGE Form 1 (US 2021), replacing the baseline instruments as requested.</li><li>Feedback questionnaires: participant respondents only, with provisional wording adaptations.</li><li>Scores are manually entered examples; no automated scoring, diagnosis, eligibility rule, score conversion or pre/post improvement calculation.</li><li>Digit Span remains available as a separate demonstration game.</li></ul><h3>Before an actual study begins</h3><p>The approved protocol must settle scoring guidance, assessment administration, consent and assistance, eligibility, session frequency, questionnaire wording and the analysis plan. This demonstration is for committee and IRB review and does not imply approval.</p><p>Screening Questions 7 and 9 currently allow one injury mechanism and multiple diagnoses respectively; those response rules are provisional. Staff eligibility review is a separate staff task, not the participant feedback questionnaire.</p></div>}

 <footer><button type="button" onClick={exportDraft}>Export review draft JSON</button><p>Export includes the screening code and all separately labelled draft test results, including other fictional participant codes entered during this session. Unsaved result-entry fields are excluded.</p></footer>
 </section>;
}
